name: SNYK x InvisiRisk
 
on:
  workflow_dispatch:
 
permissions:
  checks: write
  contents: write
  packages: read
  actions: write
 
jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    name: Sync fork and Run build
 
    steps:
      # ============= InvisiRisk Setup =============
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          app_token: ${{secrets.IR_API_KEY}}
          mode: 'docker-intercept'
          
      # ============= InvisiRisk Setup End =============
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
 
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
 
      - name: Cache NPM modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
 
      - name: Install dependencies
        run: npm install --legacy-peer-deps
 
      - name: Build Docker Image
        run: docker build -t my-app:latest --build-arg BUILDKIT_SYNTAX=kkisalaya/pse-frontend:latest \
             --secret id=pse-ca,src=/usr/local/share/ca-certificates/pse.crt \
             --build-arg PSE_PROXY=http://${PROXY_IP}:3128 .
        
      # ============= InvisiRisk Cleanup =============
      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@latest
        with:
          cleanup: "true"
      # ============= InvisiRisk Cleanup End =============
